### ISSUE TITLE
使用千万注意！

### ISSUE THREAD

**Issue by R4be1** [iamHuFei/CharVulFlow#2]
站长之家那个接口千万别买，可以自己在get_icp这个函数里改成免费的接口，我tm没过脑子直接买了站长之家的接口，白花我100md

**Comment by R4be1** [comment]
另外可能需要两天时间来调试 更改相关信息，想做到批量提交不同的漏洞的效果得自己魔改，有点小麻烦，而且ocr的接口也经常断（报错，最好自己改的时候加个while和try

**Comment by iamHuFei** [comment]
后续有时间会进一步更改，现在效果很差，仅供参考学习。
